version: '3.7'

networks:
  laravel:

services:

  cadastro_cliente:
    container_name: cadastro_cliente_container
    build:
        context: .
        dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    depends_on: 
        - redis
    networks: 
        - laravel
        
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_cliente
    port:
      - "7000:80"
    volume:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql_cliente
    restart: unless-stopped
    tty: true
    ports:
      - "3388:33306"
    environment:
      MYSQL_DATABASE: projeto_cadastro_cliente
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      -./mysql:/var/lib/mysql
  
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_cliente
    volumes:
      - .src:/var/www/html
    ports:
      - "9001:9001"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer_cliente
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - laravel
  
  npm: 
    image: node:13.7
    container_name: npm_cliente
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_cliente
    volumes: 
      - ./src:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - laravel
